from collections.abc import Iterable, Iterator, MutableMapping, MutableSequence
from typing import Any, ClassVar, Self, TypeVar, overload, override

from .line import Style, _Event

__all__ = (
    "LineSection",
    "FieldSection",
    "EventsSection",
    "StylesSection",
    "ScriptInfoSection",
)

_T = TypeVar("_T")

class LineSection(MutableSequence[_T]):
    FORMAT_TYPE: ClassVar[str]

    name: str

    def __init__(self, name: str, lines: list[_T] | None = None) -> None: ...
    def dump(self) -> Iterator[str]: ...
    def add_line(self, type_name: str, raw_line: str) -> None: ...
    def set_data(self, lines: MutableSequence[_T]) -> None: ...
    @override
    @overload
    def __getitem__(self, index: int) -> _T: ...
    @overload
    def __getitem__(self, index: slice) -> MutableSequence[_T]: ...
    @override
    @overload
    def __setitem__(self, index: int, val: _T) -> None: ...
    @overload
    def __setitem__(self, index: slice, val: Iterable[_T]) -> None: ...
    @override
    def __delitem__(self, index: int | slice) -> None: ...
    @override
    def __len__(self) -> int: ...
    @override
    def insert(self, index: int, value: _T) -> None: ...

class FieldSection(MutableMapping[str, Any]):
    name: str

    def __init__(
        self, name: str, fields: MutableMapping[str, Any] | None = None
    ) -> None: ...
    def dump(self) -> Iterator[str]: ...
    def add_line(self, type_name: str, raw_line: str) -> None: ...
    def set_data(self, fields: MutableMapping[str, Any]) -> None: ...
    @override
    def __getitem__(self, key: str) -> Any: ...
    @override
    def __setitem__(self, key: str, val: Any) -> None: ...
    @override
    def __delitem__(self, key: str) -> None: ...
    @override
    def __iter__(self) -> Iterator[str]: ...
    @override
    def __len__(self) -> int: ...
    def copy(self) -> Self: ...

class EventsSection(LineSection[_Event]): ...
class StylesSection(LineSection[Style]): ...

class ScriptInfoSection(FieldSection):
    VERSION_ASS: ClassVar[str]
    VERSION_SSA: ClassVar[str]
